#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jul 17, 2018 11:11:40 AM


import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

    import serial as com

    port = "COM1"
    baud = 115200
    ser = com.Serial(port, baud, timeout=1)

def validation():

    if ser.isOpen():
            cmd = ':01\r\n'
            ser.write(cmd.encode())
            out=ser.read(20)
            if len(out) == 0:
                messagebox.showwarning("VERSION", "NO COMMUNICATION")
            else:
                messagebox.showinfo("Serial Communication",out[1:len(out)-2])



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Serial_Comm
    Serial_Comm.vp_start_gui()


def Validation_SerialNo():
    cmd = ":12\r\n"
    ser.write(cmd.encode())
    out = ser.read(20)
    if len(out) == 0:
        messagebox.showwarning("SerialNumber","NO COMMUNICATION")
    else:
        messagebox.showinfo("SerialNumber",out[1:len(out)-2])
    #return None


def Validation_ClearMemory():
    messagebox.askokcancel("Serial Communication","Are You Clear Memory")
    cmd = ":25 1111\r\n"
    ser.write(cmd.encode())
    out = ser.read(100)
    print(out)

    if len(out) == 0:
        messagebox.showinfo("CLEAR MEMORY", "MEMORY CLEARED")
        return None
    while out:
        out = ser.read(100)
        print(out)
        if out[len(out)-5:len(out)-2] == ":52":
            messagebox.showinfo("CLEAR MEMORY","SUCCESSFULL")
            return None
        else:
            messagebox.showinfo("CLEAR MEMORY","IN PROGRESS")

    return None


def Validation_DateTime():

    return None